name: 'CLA Assistant'
on:
    issue_comment:
        types: [created]
    pull_request_target:
        types: [opened, closed, synchronize]

# Permissions for the local repo
permissions:
    actions: write
    contents: write
    pull-requests: write
    statuses: write

jobs:
    CLAAssistant:
        runs-on: ubuntu-latest
        steps:
            - name: 'CLA Assistant'
              if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
              uses: contributor-assistant/github-action@v2.5.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # The PAT used to write to the remote repo
                  PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
              with:
                  path-to-signatures: 'signatures/cla.json'
                  path-to-document: 'https://github.com/QuantForgeOrg/cla-signatures/blob/main/CLA.md'
                  branch: 'main' # Branch of the remote repo
                  remote-organization-name: 'QuantForgeOrg'
                  remote-repository-name: 'cla-signatures'
                  # Allow bots to bypass the check
                  allowlist: bot*,dependabot[bot],greenkeeper[bot]
